version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - mariadb_data:/bitnami
    environment:
      - MARIADB_USER=${USERNAME}
      - MARIADB_DATABASE=${DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./wp:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=${USERNAME}
      - WORDPRESS_DATABASE_NAME=${DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local

